using Day7;

namespace UnitTests.Days;

[TestClass]
public class Day7Tests
{
    [TestMethod]
    public void TestPart1()
    {
        const string input = """
                             .......S.......
                             ...............
                             .......^.......
                             ...............
                             ......^.^......
                             ...............
                             .....^.^.^.....
                             ...............
                             ....^.^...^....
                             ...............
                             ...^.^...^.^...
                             ...............
                             ..^...^.....^..
                             ...............
                             .^.^.^.^.^...^.
                             ...............
                             """;

        var result = Challenges.Part1(input.Split(Environment.NewLine));
        
        Assert.AreEqual(21, result);
    }
    
    [TestMethod]
    public void TestPart2()
    {
        const string input = """
                             .......S.......
                             ...............
                             .......^.......
                             ...............
                             ......^.^......
                             ...............
                             .....^.^.^.....
                             ...............
                             ....^.^...^....
                             ...............
                             ...^.^...^.^...
                             ...............
                             ..^...^.....^..
                             ...............
                             .^.^.^.^.^...^.
                             ...............
                             """;

        var result = Challenges.Part2(input.Split(Environment.NewLine));
        
        Assert.AreEqual(40, result);
    }
}